name: CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
      - main
    # Sequence of patterns matched against refs/tags
    tags: '*'

jobs:
  test:
    name: Python ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    if: "contains(github.event.head_commit.message, '+ci')"
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
        os:
          - ubuntu-latest
        arch:
          - x64
        exclude:
          - os: macOS-latest
            arch: x86
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deglib
        run: |
          python3 -m pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple deglib==0.1.48
          python3 -m pip install h5py tensorflow

      - name: Install dependencies
        run: |
          sudo apt-get install curl libcurl4-openssl-dev
      - name: Cache database and queries
        id: cache-data
        uses: actions/cache@v4
        with:
            path: data/**.h5
            key: data

      - name: Download database and queries
        if: steps.cache-data.outputs.cache-hit != 'true'
        env:
          DBSIZE: 300K
        run: |
            mkdir data
            cd data
            curl -O https://sisap-23-challenge.s3.amazonaws.com/SISAP23-Challenge/laion2B-en-clip768v2-n=$DBSIZE.h5
            curl -O http://ingeotec.mx/~sadit/sisap2024-data/public-queries-2024-laion2B-en-clip768v2-n=10k.h5
            curl -O http://ingeotec.mx/~sadit/sisap2024-data/gold-standard-dbsize=$DBSIZE--public-queries-2024-laion2B-en-clip768v2-n=10k.h5

      - name: Run Task 1
        env:
          DBSIZE: 300K
        run: |
          python3 run_task.py --dbsize $DBSIZE --compression 512 --query-file "data/public-queries-2024-laion2B-en-clip768v2-n=10k.h5"

      - name: Run Task 3
        env:
          DBSIZE: 300K
        run: |
          python3 run_task.py --dbsize $DBSIZE --compression 64 --query-file "data/public-queries-2024-laion2B-en-clip768v2-n=10k.h5"

      - name: Evaluation Results
        env:
          DBSIZE: 300K
        run: |
          python3 calc_recall.py --dbsize $DBSIZE --ground-truth data/gold-standard-dbsize\=$DBSIZE--public-queries-2024-laion2B-en-clip768v2-n\=10k.h5 
